# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://hero4earth.com
title: Human-Centered Data Scientist
email: eddy.sangwon@gmail.com
author: Sangwon Kim
description: > # "Write an awesome description for your new site here.
  사람 중심의 데이터 사이언티스트를 꿈꿉니다.
copyright: 'Copyright &copy; 2018 hero4earth. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: http://www.facebook.com/eddy.sangwon
  - title: github
    url: https://github.com/hero4earth
  - title: linkedin
    url: https://www.linkedin.com/in/hero4earth
